curl 'https://biwenger.as.com/api/v2/auth/login' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json; charset=utf-8' --data '{"email":"xusmen69@gmail.com","password":"xX22021983b"}'